[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:fastapi]
command=python -m uvicorn fastapi_app.main:app --host 0.0.0.0 --port 8000 --workers 2
directory=/app/room-booking-api
environment=DB_PATH="/data/bookings.db"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
